services:
  - type: web
    name: sarankar-developer-website
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    buildFilter:
      paths:
        - Dockerfile
        - pom.xml
        - src/**
        - .mvn/**
        - mvnw
        - mvnw.cmd
    healthCheckPath: /
    autoDeploy: true
    envVars:
      - key: PORT
        value: 8080
      - key: MONGODB_URI
        sync: false
      - key: SSL_ENABLED
        value: true
      - key: COOKIE_SECURE
        value: true
      - key: ALLOWED_ORIGINS
        value: https://sarankardevelopers.com
    disk:
      name: uploads
      mountPath: /uploads
      sizeGB: 1
    envVars:
      - key: JAVA_VERSION
        value: 17 