services:
  - type: web
    name: sarankar-developer-website
    env: java
    buildCommand: |
      apt-get update && apt-get install -y openjdk-17-jdk
      export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
      export PATH=$JAVA_HOME/bin:$PATH
      ./mvnw clean package -DskipTests
    startCommand: java -jar target/SarankarDeveloperWebsite-0.0.1-SNAPSHOT.jar
    envVars:
      - key: JAVA_HOME
        value: /usr/lib/jvm/java-17-openjdk-amd64
      - key: PATH
        value: $JAVA_HOME/bin:$PATH
      - key: PORT
        value: 8080
      - key: MONGODB_URI
        sync: false
      - key: SSL_ENABLED
        value: true
      - key: COOKIE_SECURE
        value: true
      - key: ALLOWED_ORIGINS
        value: https://sarankardevelopers.com
    healthCheckPath: /api/test/mongodb-connection
    autoDeploy: true
    disk:
      name: uploads
      mountPath: /uploads
      sizeGB: 1
    buildFilter:
      paths:
        - pom.xml
        - src/**
    envVars:
      - key: JAVA_VERSION
        value: 17 