services:
  - type: web
    name: sarankar-developer-website
    env: java
    buildCommand: ./mvnw clean package -DskipTests
    startCommand: java -jar target/SarankarDeveloperWebsite-0.0.1-SNAPSHOT.jar
    envVars:
      - key: JAVA_VERSION
        value: 17
      - key: PORT
        value: 8080
      - key: MONGODB_URI
        sync: false
      - key: SSL_ENABLED
        value: true
      - key: COOKIE_SECURE
        value: true
      - key: ALLOWED_ORIGINS
        value: https://sarankardevelopers.com
    healthCheckPath: /api/test/mongodb-connection
    autoDeploy: true
    disk:
      name: uploads
      mountPath: /uploads
      sizeGB: 1
    buildFilter:
      paths:
        - pom.xml
        - src/**
    envVars:
      - key: JAVA_VERSION
        value: 17 